### ISSUE TITLE
win10找不到cuda 0，nvidia-smi显示facechain在使用cuda 0

### ISSUE THREAD

**Issue by vawterdada** [modelscope/facechain#123]
![7e3aa8f565b74c6200462b1c3b082e4](https://github.com/modelscope/facechain/assets/130421680/573cc747-bcf4-4328-8b39-e7ea2a01ec6e)

**Comment by ultimatech-cn** [comment]
在你的环境下，进入python，尝试如下命令，看一下结果
import torch # 如果pytorch安装成功即可导入
print(torch.cuda.is_available()) # 查看CUDA是否可用，true为可用
print(torch.cuda.device_count()) # 查看可用的CUDA数量
print(torch.version.cuda) # 查看CUDA的版本号

window环境搭建可以参考https://zhuanlan.zhihu.com/p/651180440

**Comment by 1014670860** [comment]
在ubunut20中, docker启动 添加参数 `--gpus all` 会失败, 去掉后使用则报错`'CUDA is not available.'`, 点解

**Comment by gllhjy** [comment]
ubuntu20.04也遇到同样的问题

**Comment by 1014670860** [comment]
> 在ubunut20中, docker启动 添加参数 `--gpus all` 会失败, 去掉后使用则报错`'CUDA is not available.'`, 点解

解决了, 要在Ubuntu中安装显卡对应的配置, 但是训练完成还是报错
```
 File "app.py", line 109, in launch_pipeline
    style_model = styles[style_model]['name']
TypeError: list indices must be integers or slices, not NoneType
```

**Comment by 1014670860** [comment]
> ubuntu20.04也遇到同样的问题

刚pull的代码, 又跑不起来了

> > 在ubunut20中, docker启动 添加参数 `--gpus all` 会失败, 去掉后使用则报错`'CUDA is not available.'`, 点解
> 
> 解决了, 要在Ubuntu中安装显卡对应的配置, 但是训练完成还是报错
> 
> ```
>  File "app.py", line 109, in launch_pipeline
>     style_model = styles[style_model]['name']
> TypeError: list indices must be integers or slices, not NoneType
> ```

**Comment by sunbaigui** [comment]
> > 在ubunut20中, docker启动 添加参数 `--gpus all` 会失败, 去掉后使用则报错`'CUDA is not available.'`, 点解
> 
> 解决了, 要在Ubuntu中安装显卡对应的配置, 但是训练完成还是报错
> 
> ```
>  File "app.py", line 109, in launch_pipeline
>     style_model = styles[style_model]['name']
> TypeError: list indices must be integers or slices, not NoneType
> ```

pease try the latest code, see if there's still the same issue.

**Comment by 1014670860** [comment]
> 

docker环境下解决了. 要重复下载

**Comment by 1014670860** [comment]
> > > 在ubunut20中, docker启动 添加参数 `--gpus all` 会失败, 去掉后使用则报错`'CUDA is not available.'`, 点解
> > 
> > 
> > 解决了, 要在Ubuntu中安装显卡对应的配置, 但是训练完成还是报错
> > ```
> >  File "app.py", line 109, in launch_pipeline
> >     style_model = styles[style_model]['name']
> > TypeError: list indices must be integers or slices, not NoneType
> > ```
> 
> pease try the latest code, see if there's still the same issue.

谢谢! docker环境下可以了,  总之就是重试然后重新下载

**Comment by J9k9xtcejpamesgsxfki5Knepp** [comment]
p40的卡生成速度怎么样呢，无限风格生成一张图片大概需要多久呢？
